# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

cray-service:
  type: Deployment
  nameOverride: "cfs-trust"
  fullnameOverride: "cfs-trust"
  serviceAccountName: "cfstrust"
  nodeSelector:
    node-discovery.cray.com/networks.node_management: "true"
  replicaCount: 1
  containers:
    cfs-trust:
      name: "cfs-trust"
      image:
        repository: "cray/cfs-trust"
        pullPolicy: Always
      resources:
        requests:
          memory: "100Mi"
          cpu: "25m"
        limits:
          memory: "250Mi"
          cpu: "200m"
      livenessProbe:
        exec:
          command:
          - python3
          - "-m"
          - "cfsssh.setup.service.liveness"
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 10
  service:
    enabled: false
cfs-trust:
  name: "cfs-trust"
  namespace: services
  image_version: "latest"
